extensive commentary and minor fixes

diff --git a/ssync b/ssync
--- a/ssync
+++ b/ssync
@@ -19,6 +19,7 @@ assert_root
 
 #get script dir to locate settings
 script="${BASH_SOURCE[0]}"
+callname="$( basename "$script" )"
 if [[ -L "$script" ]]; then script="$( readlink -ms "$script" )"; fi
 dir="$( dirname "$script" )"
 
@@ -44,8 +45,9 @@ case "$mainarg" in
 	add|rm|check)
 		let c_ok=0 c_fail=0
 
+		#loop over arguments if multiple files given/globbed
 		while : ; do
-			#calculate resolved non-repo path
+			#normalize: calculate resolved non-repo path and strip repo
 			fullpath="$(realpath --quiet --canonicalize-missing --no-symlinks "$1")"
 			fullpath="${fullpath##"$syncrepo/files"}"
 
@@ -54,6 +56,7 @@ case "$mainarg" in
 				helphint && exit 1
 			fi
 
+			#execute and record status message
 			case "$mainarg" in
 				add) sync_add "$fullpath";;
 				rm) sync_rm "$fullpath";;
@@ -121,6 +124,7 @@ function errecho {
 }
 
 function assert_root {
+	#make sure user is root unless help or simple querying commands are called
 	if [[ $EUID -ne 0 ]] && ! [[ "$mainarg" =~ ^help|check|status|log$ ]]; then
 		errecho "This must be run as root."
 		exit 1
@@ -128,6 +132,7 @@ function assert_root {
 }
 
 function check_properly_configured {
+	#look if settings file exists and differs from template, otherwise copy it and display explanation
 	if ( test ! -f "$dir/settings.inc" ) || ( cmp -s "$dir/settings.inc.template" "$dir/settings.inc" >/dev/null ); then
 		cp "$dir/settings.inc.template" "$dir/settings.inc"
 		echo "Welcome to ssync!
@@ -142,19 +147,27 @@ function check_properly_configured {
 }
 
 function check_setup {
-	if ! [[ "$mainarg" =~ ^help|setup$ ]] && ! [[ -e "$syncrepo/.git" ]]; then
+	if [[ "$mainarg" =~ ^help|setup$ ]]; then
+		#calling help or setup does not require setup
+		return 0
+	fi
+
+	#setup is complete if local git repo exists
+	if ! [[ -e "$syncrepo/.git" ]]; then
 		errecho "ERROR: Setup not completed."
 		helphint && exit 1
 	fi
+
+	check_branch "$machinebranch"
 }
 
 function helphint {
-	errecho " => ssync help"
+	errecho " => $callname help"
 }
 
 function usagehelp () {
 	echo "
-USAGE: ssync [verbose] COMMAND
+USAGE: $callname [verbose] COMMAND
 
 COMMANDS:
     setup [new]
@@ -201,6 +214,7 @@ COMMANDS:
 }
 
 function ask_confirm {
+	#query user for positive confirmation, has a timeout which returns failure
 	local message="$1" answer
 
 	while [[ ! "$answer" =~ ^[yYnN]$ ]]; do
@@ -219,14 +233,16 @@ function ask_confirm {
 ####################    CORE FUNCTIONS    ####################
 ##############################################################
 
-function gpg_enabled {
+function is_gpg_enabled {
+	#is gpgkey configured in settings file?
 	if [[ ! -z "$gpgkey" ]]; then return 0; else return 1; fi
 }
 
 function gpg_check {
+	#makes sure given git reference is trusted
 	local testedref="$1"
 
-	if gpg_enabled; then
+	if is_gpg_enabled; then
 		echo -n "GPG check for $testedref... "
 		if ! git verify-commit "$testedref" 2>&9; then
 			errecho "\n########## GPG TRUST FAIL! ##########"
@@ -239,6 +255,7 @@ function gpg_check {
 }
 
 function is_indexed {
+	#is given entry in index file?
 	local matches
 
 	matches="$(grep --count --fixed-strings --line-regexp "$2" "$1")"
@@ -250,6 +267,7 @@ function is_indexed {
 }
 
 function add_to_index {
+	#adds entry to sorted index file
 	local indexfile="$1" location="$2"
 
 	if is_indexed "$indexfile" "$location"; then
@@ -260,18 +278,22 @@ function add_to_index {
 }
 
 function remove_from_index {
-	local indexfile="$1" location="$2"
+	#deletes entry from index file
+	local indexfile="$1" location="$2" tmpindex
 
 	if ! is_indexed "$indexfile" "$location"; then
 		errecho "WARNING: Attempt to remove non-indexed entry from $indexfile"
 	else
-		cp -a "$indexfile" "$indexfile.tmp"
-		grep --invert-match --fixed-strings --line-regexp "$location" "$indexfile.tmp" > "$indexfile"
-		rm "$indexfile.tmp"
+		#temporary copy to modify index itself
+		tmpindex="$(mktemp)"
+		cp "$indexfile" "$tmpindex"
+		grep --invert-match --fixed-strings --line-regexp "$location" "$tmpindex" > "$indexfile"
+		rm "$tmpindex"
 	fi
 }
 
 function is_child_of {
+	#tests if a path is a child of another path, normalized to non-repo path
 	local child="$1" parent="$2" reduced
 
 	#resolve links
@@ -288,6 +310,7 @@ function is_child_of {
 }
 
 function is_in_repo {
+	#is path versioned in repo?
 	local tested="$1" line
 
 	while read line; do
@@ -303,6 +326,7 @@ function is_in_repo {
 }
 
 function has_child_in_repo {
+	#are children of this path versioned in repo?
 	local parent="$1" line
 
 	while read line; do
@@ -315,6 +339,7 @@ function has_child_in_repo {
 }
 
 function add_clone_link {
+	#creates a repo-pointing link (and necessary parent directories)
 	local original="$1" link="$2"
 
 	mkdir -p "$(dirname "$link")"
@@ -328,13 +353,19 @@ function is_index_changed {
 }
 
 function save_permissions {
+	#saves versioned files' permissions to permission index
 	local line hit
 
+	#edge case: no files versioned yet
 	if [[ ! -e "$syncrepo/files" ]]; then return 0; fi
+
 	cd "$syncrepo"
 	while read -u 3 line; do
+		#gitignored files wont be synced so avoid recording their stats
 		if ! git check-ignore --quiet "$line"; then
 			hit="${line##"$syncrepo/files"}"
+			#make absolutely sure that this file is wanted
+			#probably not necessary at this point, tbh...
 			if is_in_repo "$hit" 9>/dev/null; then
 				echo "$(stat --dereference --printf="%04a:%U:%G" "$line"):$hit"
 			fi
@@ -343,12 +374,14 @@ function save_permissions {
 }
 
 function restore_permissions {
+	#restores versioned files' permissions from permission index
 	local mod user group location
 
 	echo "Adjusting permissions..."
 	while IFS=: read -u 3 -r mod user group location; do
 		location="$syncrepo/files$location"
 		if [[ -e "$location" ]]; then
+			#only change owner/permissions if they differ
 			if [[ "$user:$group" != "$(stat --printf="%U:%G" "$location")" ]]; then
 				chown --dereference --changes -- "$user:$group" "$location" >&9
 			fi
@@ -362,21 +395,25 @@ function restore_permissions {
 }
 
 function is_repo_clean {
+	#are the no changes to permissions and/or files?
 	cd "$syncrepo"
+	#update permission index so git will detect this as a file change
 	save_permissions
 	if [[ -z "$(git status --porcelain)" ]]; then return 0; else return 1; fi
 }
 
 function check_repo_clean {
+	#makes sure repository is in committed state
 	if is_repo_clean; then
 		return 0
 	else
-		errecho "[!] Aborting operation. Repository is not clean, see: ssync status"
+		errecho "[!] Aborting operation. Repository is not clean, see: $callname status"
 		exit 1
 	fi
 }
 
 function check_branch {
+	#makes sure given branch is checked out
 	local expectedbranch="$1"
 
 	if [[ "$(git symbolic-ref --short --quiet HEAD)" == "$expectedbranch" ]]; then
@@ -396,6 +433,7 @@ function sync_setup {
 	if [[ "$1" == "new" ]]; then
 		echo "SYSTEMSYNC-REPO-CREATION"
 		echo "########################"
+		#create a repository containing the ssync structures and push it
 
 		temprepo="$(mktemp -d)"
 		cd "$temprepo"
@@ -405,7 +443,7 @@ function sync_setup {
 		git checkout "$syncbranch"
 		git config user.name "ssync"
 		git config user.email "ssync@localhost"
-		if gpg_enabled; then
+		if is_gpg_enabled; then
 			git config user.signingkey "$gpgkey"
 			git config commit.gpgsign true
 		fi
@@ -421,16 +459,18 @@ function sync_setup {
 	echo "################"
 	cd "$dir"
 
-	echo "Cloning system config repo..."
+	echo "Cloning sync repository..."
 	if ! git clone --origin origin "$giturl" "$syncrepo"; then
 		errecho "CLONE FAILED." && exit 1
 	fi
 
 	echo "Setting up hooks..."
+	#these hooks trigger ssync fix on every working tree update which updates permissions and local files
 	echo -e "#!/bin/bash\n$dir/ssync fix" > "$syncrepo/.git/hooks/post-checkout"
 	chmod u+x "$syncrepo/.git/hooks/post-checkout"
 	cp "$syncrepo/.git/hooks/post-checkout" "$syncrepo/.git/hooks/post-merge"
 
+	#if configured this creates an alias for ssync
 	if [[ ! -z "$programlink" ]]; then
 		echo "(Re)Linking in /usr/local/bin as $programlink..."
 		rm "/usr/local/bin/$programlink" 2> /dev/null
@@ -438,18 +478,22 @@ function sync_setup {
 	fi
 
 	echo "Setting up local repository..."
+
 	cd "$syncrepo"
 	git config user.name "$gituser"
 	git config user.email "$gitemail"
 	git config push.default matching
-	#Versioning files exactly as-is, apart from file (handled by permission restoration)
+
+	#Versioning files exactly as-is, apart from file mode (handled by permission restoration)
 	git config core.autocrlf false
 	git config core.whitespace ""
 	git config core.fileMode false
-	if gpg_enabled; then
+
+	if is_gpg_enabled; then
 		git config user.signingkey "$gpgkey"
 		git config commit.gpgsign true
 	fi
+
 	gpg_check "origin/$syncbranch"
 	git checkout "$syncbranch"
 	git branch -u "origin/$syncbranch"
@@ -500,7 +544,7 @@ function sync_rm {
 	repodata="$syncrepo/files$passed"
 
 	if ! is_indexed "$syncrepo/$linkindex" "$passed"; then
-		errecho "ERROR, no repository link (see: ssync links)"
+		errecho "ERROR, no repository link (see: $callname links)"
 	elif [[ ! -L "$passed" ]]; then
 		errecho "ERROR, no symlink encountered"
 		errecho "WARNING: $syncrepo/$linkindex corrupt. Link missing!"
@@ -539,10 +583,11 @@ function sync_status {
 			echo "No uncommitted changes."
 			return 0
 		elif [[ "$(git status --porcelain)" =~ ^.." $permfile"$ ]]; then
+			#if the only changes that git discovers are in the permission index:
 			echo "There are uncommitted permission changes but no file changes."
 			return 1
 		else
-			echo "There are uncommitted file changes. (for details: ssync git status)"
+			echo "There are uncommitted file changes. (for details: $callname git status)"
 			return 1
 		fi
 	else
@@ -568,6 +613,8 @@ function sync_fix {
 	while read -u 4 location; do
 		target="$syncrepo/files$location"
 		echo -n "$location => " >&9
+
+		#Local path is a symlink, handle conflict if not pointing to repo
 		if [[ -L "$location" ]]; then
 			reallocation="$(realpath --quiet --canonicalize-missing "$location")"
 			if [[ "$reallocation" == "$syncrepo/files/"* ]]; then
@@ -581,6 +628,8 @@ function sync_fix {
 					|| { errecho "Correcting link failed."; ((problems++)); }
 				else ((problems++)); fi
 			fi
+
+		#otherwise confirm if existing contents can be removed
 		elif [[ -e "$location" ]]; then
 			echo "CONTENT CONFLICT!" >&9
 			errecho "Symlink to repository expected but file/folder found: $location"
@@ -589,6 +638,8 @@ function sync_fix {
 				&& add_clone_link "$target" "$location" ) \
 				|| { errecho "Linking failed."; ((problems++)); }
 			else ((problems++)); fi
+
+		#last possibility: nothing present so simply add the missing link
 		else
 			echo "adding..." >&9
 			echo "Restoring missing link: $location" \
@@ -597,11 +648,14 @@ function sync_fix {
 		fi
 	done 4<"$syncrepo/$linkindex"
 
-	restore_permissions
+
 	if (( $problems > 0 )); then
-		errecho "[!] WARNING: $problems problem(s) unresolved and remaining. Re-run \"ssync fix\" to check again."
+		errecho "[!] WARNING: $problems problem(s) unresolved and remaining. Re-run \"$callname fix\" to check again."
 		return 1
 	else
+		#all links are in their correct place, therefore:
+		restore_permissions
+
 		echo "[i] Repository state clean."
 		return 0
 	fi
@@ -613,26 +667,27 @@ function sync_log {
 
 function sync_update {
 	local verify
-	if gpg_enabled; then verify="--verify-signatures"; fi
+	if is_gpg_enabled; then verify="--verify-signatures"; fi
 
 	if [[ -e "$syncrepo/.git/MERGE_HEAD" ]]; then
-		errecho "[!] Merge not complete. Fix and run: ssync commit"
+		errecho "[!] Merge not complete. Fix and run: $callname commit"
 		return 1
 	else
+		#fetch sync branch, check signatures, update local pointer without checking out and finally merge in changes
 		cd "$syncrepo" \
 		&& git fetch origin \
 		&& check_repo_clean \
-		&& git checkout --quiet "$machinebranch" \
 		&& gpg_check "$machinebranch" \
 		&& gpg_check "origin/$syncbranch" \
 		&& git branch --quiet -f "$syncbranch" "origin/$syncbranch" \
 		&& { git merge --ff $verify "$syncbranch" && echo "[i] Updated from central repository." && return 0 \
-		     || { errecho "[!] Merge needs manual intervention. Do so and run: ssync commit" && return 1; }; } \
+		     || { errecho "[!] Merge needs manual intervention. Do so and run: $callname commit" && return 1; }; } \
 		|| { errecho "[!] Update failed." && return 1; }
 	fi
 }
 
 function sync_publish {
+	#update (pull+merge) and push - that's all!
 	cd "$syncrepo" \
 	&& echo "Updating..." \
 	&& sync_update > /dev/null \
@@ -647,7 +702,7 @@ function sync_uninstall {
 	echo "This will restore all the content that is currently controlled by ssync and delete the local repository ($syncrepo)."
 	if ask_confirm "Are you ABSOLUTELY sure you want to do this?" && ask_confirm "Seriously, you understand the consequences and want to proceed?"; then
 		if [[ -s "$syncrepo/$linkindex" ]]; then
-			"$script" verbose rm $(cat "$syncrepo/$linkindex")
+			"$dir/ssync" verbose rm $(cat "$syncrepo/$linkindex")
 		fi
 		if [[ -s "$syncrepo/$linkindex" ]]; then
 			errecho "\n[!] Something went wrong. Aborting uninstall."
@@ -662,21 +717,22 @@ function sync_uninstall {
 
 function sync_reset {
 	cd "$syncrepo"
-	check_branch "$machinebranch"
 
 	if ask_confirm "All uncommitted changes will be lost. Continue?"; then
 		  added="$(git --no-pager diff "$linkindex" | grep --only-matching --color=never -P "^[+]\K/.+$")"
 		removed="$(git --no-pager diff "$linkindex" | grep --only-matching --color=never -P "^[-]\K/.+$")"
 
+		#Undo ssync add/rm since last commit
 		if [[ ! -z "$added"   ]]; then
 			echo -e "Added since commit:\n$added\nRestoring..."
-			"$script" rm  $added
+			"$dir/ssync" rm  $added
 		fi
 		if [[ ! -z "$removed" ]]; then
 			echo -e "Removed since commit:\n$removed\nRelinking..."
-			"$script" add $removed
+			"$dir/ssync" add $removed
 		fi
 
+		#If correctly undone reset git
 		if ! is_index_changed; then
 			echo "Resetting git..."
 			git reset --hard "$machinebranch" \
